CREATE DATABASE WordleDB;
GO

USE WordleDB;
GO

CREATE TABLE [Users] (
    Id INT PRIMARY KEY IDENTITY,
    Email NVARCHAR(100) NOT NULL UNIQUE,
    PasswordHash NVARCHAR(256) NOT NULL
);

CREATE TABLE [Games] (
    Id INT PRIMARY KEY IDENTITY,
    UserId INT NOT NULL,
    TargetWord CHAR(5) NOT NULL,
    StartDate DATETIME2 NOT NULL DEFAULT GETDATE(),
    EndDate DATETIME2 NULL,
    Attempts INT NOT NULL DEFAULT 0,
    IsWin BIT NOT NULL DEFAULT 0,
    FOREIGN KEY (UserId) REFERENCES Users(Id)
);

CREATE TABLE [Guesses] (
    Id INT PRIMARY KEY IDENTITY,
    GameId INT NOT NULL,
    Word CHAR(5) NOT NULL,
    GuessNumber INT NOT NULL,
    GuessResult NVARCHAR(20) NOT NULL,
    FOREIGN KEY (GameId) REFERENCES Games(Id)
);

CREATE TABLE [Statistics] (
    Id INT PRIMARY KEY IDENTITY,
    UserId INT NOT NULL UNIQUE,
    GamesPlayed INT NOT NULL DEFAULT 0,
    Wins INT NOT NULL DEFAULT 0,
    CurrentStreak INT NOT NULL DEFAULT 0,
    MaxStreak INT NOT NULL DEFAULT 0,
    TotalPoints INT NOT NULL DEFAULT 0,
    FOREIGN KEY (UserId) REFERENCES Users(Id)
);
